baseURL = 'https://highlandhideaway.ca/'
title = 'Highland Hideaway'
theme = 'DoIt'

# Language settings
defaultContentLanguage = "en"
languageCode = 'en-us'

# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    title = ""
  [[menu.main]]
    weight = 2
    identifier = "about"
    name = "About"
    url = "/about/"
    title = ""

[params]
  # DoIt theme version
  version = "0.4.0"
  # site default theme ("light", "dark", "auto")
  defaultTheme = 'auto'
  # date format
  dateFormat = "2006-01-02"
  # website title for Open Graph and Twitter Cards
  title = "Highland Hideaway"
  # website description for RSS, SEO, Open Graph and Twitter Cards
  description = 'A peaceful retreat in the heart of the Highlands'
  keywords = 'cottage, vacation, highlands, retreat'
  
  # Home profile config
  [params.home.profile]
    avatarURL = "/images/site-avatar.png"
    title = "Highland Hideaway"
    subtitle = "A peaceful retreat"
  
  # Author config
  [params.author]
    name = "Highland Hideaway"
    email = ""
    link = ""

  # SEO config
  [params.seo]
    # images for Open Graph and Twitter Cards
    images = []
    # Twitter Cards config
    [params.seo.twitter]
      # Twitter Card type ("summary", "summary_large_image")
      card = "summary"

  # Analytics config
  [params.analytics]
    # Google Analytics
    google = ""
    # Fathom Analytics
    fathom = ""
    # Baidu Analytics
    baidu = ""
    # Umami Analytics
    umami = ""
    # Plausible Analytics
    plausible = ""
    # Cloudflare Web Analytics
    cloudflare = ""
    # Splitbee Analytics
    splitbee = ""

  # Comment config
  [params.comment]
    # Disqus comment system
    disqus = ""
    # Gitalk comment system
    [params.comment.gitalk]
      owner = ""
      repo = ""
      clientId = ""
      clientSecret = ""
    # Valine comment system
    [params.comment.valine]
      appId = ""
      appKey = ""
      placeholder = ""
    # Waline comment system
    [params.comment.waline]
      serverURL = ""
      lang = ""
      emoji = []
    # Facebook comment system
    [params.comment.facebook]
      appId = ""
      userID = ""
      pageID = ""
    # Telegram comment system
    [params.comment.telegram]
      siteID = ""
      limit = 5
      height = ""
      color = ""
    # Commento comment system
    [params.comment.commento]
      url = ""
    # Utterances comment system
    [params.comment.utterances]
      repo = ""
    # Twikoo comment system
    [params.comment.twikoo]
      envId = ""
      region = ""
      path = ""
    # Vssue comment system
    [params.comment.vssue]
      owner = ""
      repo = ""
      clientId = ""
      clientSecret = ""
    # Remark42 comment system
    [params.comment.remark42]
      host = ""
      site_id = ""
      max_shown_comments = 15
      theme = "light"
    # Giscus comment system
    [params.comment.giscus]
      repo = ""
      repoId = ""
      category = ""
      categoryId = ""
      mapping = "pathname"
      reactionsEnabled = "1"
      emitMetadata = "0"
      inputPosition = "bottom"
      theme = "light"
    # Artalk comment system
    [params.comment.artalk]
      server = ""
      site = ""
      placeholder = ""
      noComment = ""
      sendBtn = ""
      editorTravel = true
      flatMode = false
      maxNesting = 3
      pageKey = ""
      pageTitle = ""
      pageAdmin = ""
      pageAdminMail = ""
      gravatar = ""
      avatar = ""
      vote = true
      voteDown = false
      uaBadge = true
      listSort = "date_desc"
      preview = true
      countEl = "#ArtalkCount"
      pvEl = "#ArtalkPV"
      lightbox = true
      heightLimit = 2500
      imgUpload = true
      imgUploader = ""
      emoticons = ""

[build]
  writeStats = true
  noChmod = true
  noTimes = true
